eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8097/eureka


spring:
  cloud:
    gateway:
      routes:
        - id: reservationModule
          uri: lb://reservation-service
          predicates:
            - Path=/reservation/**

        - id: carModule
          uri: lb://car-service
          predicates:
            - Path=/car/**

        - id: logModule
          uri: lb://log-service
          predicates:
            - Path=/log/**