
server:
  port: 8097

  #Eureka client need to register with eureka server to become discoverable.
  #Eureka server can act as client as well. So setting
  #registerWith Eureka and fetchRegistry to false is mandatory

#Only clients need to fetch registry to get the registered
#microservices for communication EurekaServer need not register
#itself and also need not fetch other registered Microservices

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/